apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.persistence.claimName }}

  labels:
    app: {{ template "wordpress.fullname" . }}
    chart: {{ template "wordpress.chart" . }}
    release: {{ .Release.Name |quote}}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }} 
