apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: {{ template "wordpress.fullname" . }}
    tier: mysql
  clusterIP: None
