apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress-mysql
  labels:
    app: {{ template "wordpress.fullname" . }}
    chart: {{ template "wordpress.chart" . }}
    release: {{ .Release.Name |quote}}
spec:
  selector:
    matchLabels:
      app: {{ template "wordpress.fullname" . }}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "wordpress.fullname" . }}
        tier: mysql
    spec:
      containers:
      - image: {{ .Values.apps.mysql.image }}:{{ .Values.apps.mysql.tag }}
        name: {{ .Chart.Name }}-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.db.rootpassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.db.name }}
        - name: MYSQL_USER
          value: {{ .Values.db.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.db.password }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.db.persistence.claimName }}


