apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
  labels:
    app: {{ template "wordpress.fullname" . }} 
    chart: {{ template "wordpress.chart" . }} 
    release: {{ .Release.Name |quote}} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }} 
