apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ template "wordpress.fullname" . }}
    chart: {{ template "wordpress.chart" . }}
    release: {{ .Release.Name |quote}}
spec:
  selector:
    matchLabels:
      app: {{ template "wordpress.fullname" . }}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "wordpress.fullname" . }}
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.apps.wordpress.image }}:{{ .Values.apps.wordpress.tag }}
        name: {{.Chart.Name }}-wordpress
        resources:
              requests:
                memory: {{ .Values.resources.wordpress.memory | quote }}
                cpu: {{ .Values.resources.wordpress.cpu | quote }}

        env:
        - name: WORDPRESS_DB_HOST
          value:  {{ .Values.db.host }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.db.password  }}
        - name: WORDPRESS_DB_USER
          value:  {{ .Values.db.user }}
        - name: WORDPRESS_DEBUG
          value: {{ .Values.debug | quote }}
        ports:
        - containerPort: {{ .Values.service.wordpress.internalPort}}
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}

