appName: wp1
apps:
        wordpress:
                image: wordpress
                tag: 6.2.1-apache
        mysql:
                image: mysql
                tag: "8.0"
persistence:
        size: 1Gi
        claimName: wp-pvc1
        accessMode: ReadWriteOnce

db:
        name: wordpress
        host: wordpress-mysql
        user: wordpress
        password: password
        rootpassword: rutpassword
        persistence:
                size: 1Gi
                claimName: my-pvc1
                accessMode: ReadWriteOnce
service:
        wordpress:
                internalPort: 80


resources:
        wordpress:
                memory: 500Mi
                cpu: 500m

